"""CRM Integration Agent package."""

from .client import (
    CRMIntegrationClient,
    CRMIntegrationError,
    ChannelName,
    ConsentRecord,
    ConsentRequiredError,
    Contact,
    ConversationMessage,
    ConversationThread,
    DirectionName,
    EnvironmentName,
    ProviderConfig,
    ProviderError,
    ProviderName,
    RateLimitError,
    SyncResult,
    ValidationError,
    audit_template,
    build_dedupe_key,
    canonical_email,
    classify_business_purpose,
    classify_message_direction,
    dedupe_messages,
    extract_crm_id,
    format_il_date,
    handle_response,
    is_business_hours_il,
    is_explicit_opt_in_text,
    is_opt_out_text,
    load_thread_file,
    load_thread_from_mapping,
    make_idempotency_key,
    normalize_channel,
    normalize_israeli_phone,
    normalize_name,
    parse_datetime,
    parse_il_date,
    provider_token_from_env,
    redact_sensitive_text,
    result_to_dict,
    split_hebrew_name,
    write_audit_events,
)

__all__ = [name for name in globals() if not name.startswith("_")]
__version__ = "1.3.0"
