"""Terminology Glossary Builder package."""
from .client import (
    SOURCE_REGISTRY,
    TERM_LIBRARY,
    Audience,
    CitationSource,
    Environment,
    GlossaryBuilder,
    GlossaryEntry,
    GlossaryResult,
    GlossaryStore,
    LanguageMode,
    OutputFormat,
    build_glossary_json,
    build_sample_terms,
    detect_language,
    make_glossary_id,
    normalize_term,
    today_il,
    unique_preserve_order,
    validate_environment,
)

__version__ = "1.1.0"

__all__ = [
    "Audience",
    "CitationSource",
    "Environment",
    "GlossaryBuilder",
    "GlossaryEntry",
    "GlossaryResult",
    "GlossaryStore",
    "LanguageMode",
    "OutputFormat",
    "SOURCE_REGISTRY",
    "TERM_LIBRARY",
    "build_glossary_json",
    "build_sample_terms",
    "detect_language",
    "make_glossary_id",
    "normalize_term",
    "today_il",
    "unique_preserve_order",
    "validate_environment",
]
