"""Installable interface for HR Compliance Advisor."""

__version__ = "2.2.0"
from .client import (
    AsyncHRComplianceClient,
    ComplianceConfig,
    ComplianceFinding,
    EmployeeFacts,
    HRComplianceClient,
    InputValidationError,
    RiskLevel,
    config_from_env,
    missing_facts,
    overall_risk,
    report_to_markdown,
    required_notice_days,
    review_contractor_status,
    review_minimum_wage,
    review_notice_and_termination,
    review_overtime_and_rest,
    review_pension_and_severance,
    review_policy,
    review_protected_status,
    review_sector_orders,
    review_text_red_flags,
    validate_facts,
)

__all__ = [
    "__version__",
    "AsyncHRComplianceClient",
    "ComplianceConfig",
    "ComplianceFinding",
    "EmployeeFacts",
    "HRComplianceClient",
    "InputValidationError",
    "RiskLevel",
    "config_from_env",
    "missing_facts",
    "overall_risk",
    "report_to_markdown",
    "required_notice_days",
    "review_contractor_status",
    "review_minimum_wage",
    "review_notice_and_termination",
    "review_overtime_and_rest",
    "review_pension_and_severance",
    "review_policy",
    "review_protected_status",
    "review_sector_orders",
    "review_text_red_flags",
    "validate_facts",
]
